# Generated by Django 4.2.11 on 2024-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('user_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
