# Generated by Django 5.0.1 on 2024-01-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
